name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: 

jobs:
  build:
    env:
      TEST_OUTPUT_PATH: alternate-location
    runs-on: windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: MsBuild
        run: |
           cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\src\.build\build.xml /t:CI /p:Configuration=Debug
           echo $Env:GITHUB_WORKSPACE\src\.build\artifacts\Nhs.Ui
     
      - name: Upload Unit Tests artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: src\.build\artifacts\TestResults.html
          if-no-files-found: error
     
      - name: Upload Web artifact
        uses: actions/upload-artifact@v2
        with:
          name: web-package
          path: src\.build\artifacts\Nhs.Ui
          if-no-files-found: error

